
list.txt: format_list.txt pref_sorter.py
	cat format_list.txt | python3 pref_sorter.py > list.txt

format_list.txt: words.txt format_sorter.py
	cat words.txt | python3 format_sorter.py > format_list.txt
